from DB.transactions import add_source

add_source("APPLE", "Data on mobility via mobile phone tracker")
add_source("ONS",   "Operados Nacional do Sistema Eletrico - Brasil")
add_source("JHU",   "John Hopkins University - Covid-19 International Data")
add_source("IBGE",  "Instituto Brasileiro de Geografia e Estatistica")
add_source("PNAD_COVID", "Pesquisa Nacional de Amostra de Domicílios - Covid, IBGE")
add_source("BCB",   "Banco Central do Brasil")
add_source("IPEA",  "Instituto de Pesquisa de Economia Aplicada")
add_source("CEPEA", "Centro de Estudos Avançados em Economia Aplicada")
add_source("FRED",  "Federal Research Economic Data")
add_source("BCB_exp", "Banco Central do Brasil, Expectativas de Mercado")
add_source("FGV", "Fundação Getúlio Vargas, Dados Publicos")
add_source("BCB_VENCIMENTOS", "Banco Central do Brasil, Dados Vencimentos dos Títulos Públicos")
add_source("BEA", "Bureau of Economics Analysis")
